TODO: Revert this later. Outcommenting pdf report because my laptop misses some module
Traceback (most recent call last):
  File /home/loy/ros/indigo/system/src/challenge_manipulation/src/manipulation.py, line 48, in <module>
    import pdf
  File /home/loy/ros/indigo/repos/https_/github.com/tue-robotics/tue_robocup.git/challenge_manipulation/src/pdf.py, line 4, in <module>
    from xhtml2pdf import pisa
  File /usr/local/lib/python2.7/dist-packages/xhtml2pdf/pisa.py, line 3, in <module>
    from xhtml2pdf.document import pisaDocument
  File /usr/local/lib/python2.7/dist-packages/xhtml2pdf/document.py, line 2, in <module>
    from xhtml2pdf.context import pisaContext
  File /usr/local/lib/python2.7/dist-packages/xhtml2pdf/context.py, line 23, in <module>
    import xhtml2pdf.parser
  File /usr/local/lib/python2.7/dist-packages/xhtml2pdf/parser.py, line 17, in <module>
    from html5lib import treebuilders, inputstream
ImportError: cannot import name inputstream